### ISSUE TITLE
Tagging AMI fails

### ISSUE THREAD

**Issue by Wibles** [verbnetworks/terraform-aws-opnsense-image#1]
Nice tool.

One small error at the end

```
Error: Error applying plan:

1 error(s) occurred:

* null_resource.instance-snapshot-tag: Error running command '      export AWS_ACCESS_KEY_ID=************
      export AWS_SECRET_ACCESS_KEY=***********************
      aws --region=eu-west-1 ec2 create-tags \
          --resources  \
          --tags Key=Name,Value="OPNsense 18.7 - 20180810Z182949"
    ': exit status 255. Output:
An error occurred (MissingParameter) when calling the CreateTags operation: The request must contain the parameter resourceIdSet
````

Seems the resources variable does not get set in my environment properly. Fixed by just commenting out. that section and rerunning. AMI works, thanks.

**Comment by ndejong** [comment]
Thanks for reporting - it's one of those things that seems to work for me though :(

Could I ask for your assistance in tracking this down by providing the content of the JSON file located here `/tmp/opnsense-<build_id>-image-action.json` where the <build_id> is replaced with the relevant `build_id` which you see the error as described.

My sense is that this JSON output is not being selected correctly by `jq` to obtain the `instance-id` value, which should be happening [here](https://github.com/verbnetworks/terraform-aws-opnsense-image/blob/master/main.tf#L333)

**Comment by Wibles** [comment]
I think I found the error... I have access keys for one AWS account and cross-account permissions. I wanted to build the AMI in another account so added a profile in the aws block. I suspect this caused the error.

Also, after I reverted to your recommended approach by building a single `module`, no AMIs I make can launch instances that I can connect to. The security groups and acls are open, but can't connect to port 22 from anywhere. Network connectivity appears down in my environment even from an adjacent instance in the same subnet and security group.

It's a nice way to build AMIs, though.

**Comment by ndejong** [comment]
Okay, I'd like to dig deeper - could you advise which AMI (and hence region) you are starting with as the base

**Comment by Wibles** [comment]
Everything is left with your defaults, but I'm using EU-WEST-1 as a test region. I can share the AMI with you...

**Comment by Wibles** [comment]
This is the AMI that the builder used: ami-0b6e0ca6d4bd37b5c in EU-WEST-1

**Comment by Wibles** [comment]
Wondering if it assumes it is still on the default network 192.168.0.1? I'll test that.

**Comment by Wibles** [comment]
Closing this in favour of a new issue to deal with connectivity post-build Issue #2
